pre_prompts:
    - 'a cartoon of'
    - 'a painting of'
    - 'a watercolor of'
    - 'a comic of'
    - 'a stencil of'
    - 'a picture of'
    - 'a sculpture of'
    - 'a drawing of'
    - ''
prompts:
    - 'planet earth'
    - 'a man playing guitar'
    - 'a fruit salad'
    - 'a robot'
    - 'cats in the pool'
    - 'an astronaut'
    - 'people dancing'
    - 'a flower'
    - 'a tree'
    - 'a bird'
    - 'a sunset'
    - 'a bush'
    - 'a sunrise'
    - 'a boat'
    - 'a beach'
    - 'the sky'
    - 'cows in a field'
    - 'a red car'
style:
